/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class RedisClient {
  constructor(url: string)
  reconnect(): void
  cmdGet(key: string): string | null
  cmdSet(key: string, value: string): void
  cmdLpush(key: string, value: Array<string>): void
  cmdLpop(key: string, count: number): Array<string> | null
  cmdHset(key: string, field: string, value: string): void
  cmdHget(key: string, field: string): string | null
  cmdHgetall(key: string): Record<string, string> | null
  cmdExpire(key: string, seconds: number): void
  cmdDel(key: string): void
  cmdDelMultiple(keys: Array<string>): void
  cmdKeys(pattern: string): Array<string>
  connectionIsOpen(): boolean
}
